version: 2.1

orbs:
  python: circleci/python@2.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          command: |
            pip install pytest
            pytest --junitxml=test-results/junit.xml HW1-TestingTriangleClassification.py
      - store_test_results:
          path: test-results

workflows:
  testing_triangles:
    jobs:
      - build-and-test